# Generated by Django 3.0.2 on 2020-02-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='')),
                ('Student_Id', models.IntegerField()),
                ('National_Id', models.IntegerField()),
                ('Identity_Id', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='')),
                ('Service', models.CharField(max_length=50, verbose_name='')),
                ('WorkPlace', models.CharField(max_length=50, verbose_name='')),
                ('Assistance', models.CharField(max_length=50, verbose_name='')),
                ('Section', models.CharField(max_length=50)),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='')),
                ('Backup_Mail', models.EmailField(max_length=254, verbose_name='')),
            ],
            options={
                'verbose_name': 'ایمیل کارمندان',
                'verbose_name_plural': 'ایمیل های کارمندان',
            },
        ),
        migrations.CreateModel(
            name='StudentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='نام')),
                ('Last_Name', models.CharField(max_length=50, verbose_name=' نام خانوادگی')),
                ('Student_Id', models.IntegerField(verbose_name='شماره دانشجویی')),
                ('National_Id', models.IntegerField(verbose_name='کد ملی')),
                ('Phone_Number', models.IntegerField(verbose_name='شماره همراه')),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='دانشکده')),
                ('Section', models.CharField(max_length=50, verbose_name='مقطع تحصیلی')),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='ایمیل در خواستی')),
                ('Backup_Mail', models.EmailField(max_length=254, verbose_name='ایمیل پشنیبانی')),
            ],
            options={
                'verbose_name': 'ایمبل دانشجویان',
                'verbose_name_plural': 'ایمبل های دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='TeacherMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='')),
                ('Student_Id', models.IntegerField()),
                ('National_Id', models.IntegerField()),
                ('Identity_Id', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='')),
                ('Service', models.CharField(max_length=50, verbose_name='')),
                ('Section', models.CharField(max_length=50)),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='')),
                ('Backup_Mail', models.EmailField(max_length=254, verbose_name='')),
            ],
            options={
                'verbose_name': 'ایمیل اساتید',
                'verbose_name_plural': 'ایمیل های اساتید',
            },
        ),
    ]
