# Generated by Django 3.0.2 on 2020-01-14 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='CreateTime',
        ),
        migrations.AddField(
            model_name='emails',
            name='Create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emails',
            name='WorkPlace',
            field=models.CharField(default='KHU', max_length=50, verbose_name=''),
        ),
    ]
