# Generated by Django 3.0.2 on 2020-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemail',
            name='Assistance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Backup_Mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='College',
            field=models.CharField(default='KHU', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Request_Mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='WorkPlace',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Backup_Mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='College',
            field=models.CharField(default='KHU', max_length=50),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Request_Mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Service',
            field=models.CharField(max_length=50),
        ),
    ]
