# Generated by Django 3.0.2 on 2020-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200205_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemail',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='employeemail',
            name='Student_Id',
        ),
        migrations.RemoveField(
            model_name='teachermail',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='teachermail',
            name='Student_Id',
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Assistance',
            field=models.CharField(max_length=50, verbose_name='ذیل کدام معاونت فعالیت می کنید'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Backup_Mail',
            field=models.EmailField(max_length=254, verbose_name='ایمیل پشنیبانی'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='College',
            field=models.CharField(default='KHU', max_length=50, verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='First_Name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Identity_Id',
            field=models.IntegerField(verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='National_Id',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Phone_Number',
            field=models.IntegerField(verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Request_Mail',
            field=models.CharField(max_length=50, verbose_name='ایمیل در خواستی'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='Service',
            field=models.CharField(max_length=50, verbose_name='نوع استخدام'),
        ),
        migrations.AlterField(
            model_name='employeemail',
            name='WorkPlace',
            field=models.CharField(max_length=50, verbose_name='محل خدمت'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Backup_Mail',
            field=models.EmailField(max_length=254, verbose_name='ایمیل پشنیبانی'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='College',
            field=models.CharField(default='KHU', max_length=50, verbose_name='دانشکده محل تدریس'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='First_Name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Identity_Id',
            field=models.IntegerField(verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Last_Name',
            field=models.CharField(max_length=50, verbose_name=' نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='National_Id',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Phone_Number',
            field=models.IntegerField(verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Request_Mail',
            field=models.CharField(max_length=50, verbose_name='ایمیل در خواستی'),
        ),
        migrations.AlterField(
            model_name='teachermail',
            name='Service',
            field=models.CharField(max_length=50, verbose_name='نوع استخدام'),
        ),
    ]
