# Generated by Django 3.0.2 on 2020-01-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200114_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emails',
            new_name='email',
        ),
    ]
