# Generated by Django 3.0.2 on 2020-01-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200131_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='IdNumber',
            new_name='Id_Number',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
    ]
