# Generated by Django 3.0.2 on 2020-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20200131_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='')),
                ('Student_Id', models.IntegerField()),
                ('National_Id', models.IntegerField()),
                ('Identity_Id', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='')),
                ('Service', models.CharField(max_length=50, verbose_name='')),
                ('WorkPlace', models.CharField(max_length=50, verbose_name='')),
                ('Assistance', models.CharField(max_length=50, verbose_name='')),
                ('Section', models.CharField(max_length=50)),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='')),
                ('BackupM_ail', models.EmailField(max_length=254, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='StudentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='')),
                ('Student_Id', models.IntegerField()),
                ('National_Id', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='')),
                ('Section', models.CharField(max_length=50)),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='')),
                ('BackupM_ail', models.EmailField(max_length=254, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='TeacherMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='')),
                ('Student_Id', models.IntegerField()),
                ('National_Id', models.IntegerField()),
                ('Identity_Id', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('College', models.CharField(default='KHU', max_length=50, verbose_name='')),
                ('Service', models.CharField(max_length=50, verbose_name='')),
                ('Section', models.CharField(max_length=50)),
                ('Request_Mail', models.CharField(max_length=50, verbose_name='')),
                ('BackupM_ail', models.EmailField(max_length=254, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.DeleteModel(
            name='email',
        ),
    ]
